### PR TITLE
Numpy load class

### PR DESCRIPTION
**Pull request by dania-vera**

### CODE REVIEW

**Comment by dania-vera** [comment]
@Oceania2018 This isn't finished yet

**Comment by Oceania2018** [comment]
Could you add unit test?

**Comment by dania-vera** [comment]
@Obrain2016  I was tested it in another project. I'll do that

**Comment by Oceania2018** [comment]
OK, sounds great.

**Comment by dania-vera** [comment]
@Oceania2018  I just pushed a test. But still don't finish all the work. I need more time to test other things and organize everything better

**Pull request merged**
