### PR TITLE
Scalar api, ndarray.sum fixed, backend casting.

### PR DESCRIPTION
**Pull request by Nucs**
Hey, commit's descriptions describe exactly what was done.
`np.ones`, `np.zeros` were rewritten to fallback into a single method and `np.ones` implementation fixed. it failed in different dtype cases like `np.ones(np.uint8, ...)`.

I had to change `NDArray.Storage` to internal (from protected) to gain access in the backend engine.

I've added a backend method name Cast as progress with upcasting during math operations (#281).

Note: backend.Sum is still broken for types other than int32 (no due to my changes).

### CODE REVIEW

**Comment by Oceania2018** [comment]
Amazing work. Too much changes. Might need @henon help review.

**Comment by henon** [comment]
looks all very professional. lots of test cases too, great. I like the idea of linking to the numpy docs. 

one hint: when fixing a bug that wasn't covered by the test suite add a simple test so that it stays fixed forever.

**Comment by henon** [comment]
@Nucs: can you add an issue about the broken Sum ?

**Comment by Nucs** [comment]
Well, the backend is a mess.
No unit tests at all.
Implementations are limited to rank 2.
The types handling covers only half, sometimes just two or three types.

This has to be done next, I'm looking for a proper and clean way to handle code generations except for T4 templates.

Manually writing it all will take couple of straight days of work.
If anyone knows what tool the dev used [here](https://github.com/arrayfire/arrayfire-dotnet/blob/b536d0b36c2d317d6f356f4abcb28c9f55afa6af/src/Wrapper/Data.cs#L44) - that would be great.

**Comment by Oceania2018** [comment]
They use F# to generate the code.

**Comment by Oceania2018** [comment]
Found nest loop for np.ones. I've fixed it.

**Comment by Oceania2018** [comment]
@Nucs Please always keep in mind the performance. for example.

```csharp
           Single SumSingle(Single[] arr)
            {
                Single sum = 0;
                checked
                {
                    for (int i = 0; i < arr.Length; i++)
                    {
                        sum += arr[i];
                    }
                }

                return sum;
            }
```
At most of time, the Linq `sum` would faster than raw loop.

You can write a performance benchmark:

image

**Comment by Nucs** [comment]
Didn't even have that project loaded, definitely will do.

**Pull request merged**
