### PR TITLE
Slice: implemented numpy slice notation

### PR DESCRIPTION
**Pull request by henon**
Damn it, Visual Studio did a white space conversion. Very inconvenient.

### CODE REVIEW

**Comment by vunb** [comment]
@henon @Oceania2018 It's due to git convention dealing with line endings. We should add `.gitattributes` file to avoid this problem. Check it here https://help.github.com/en/articles/dealing-with-line-endings

Here is my configuration for pet project: https://github.com/yeuai/YeuAI.NET/blob/master/.gitattributes

**Comment by henon** [comment]
I guess mixed line endings don't matter for C# so `core.autocrlf false` would suffice. Visual Studio likes to ask if it should convert line endings but that can be turned off. 

Most important is not what the line endings are, most important is that we get a clean diff for every commit.

**Comment by vunb** [comment]
You are right. But when we use `.gitattributes` with auto text line endings. It will help us write code on different OS Windows or Linux, more contributors can join project without thinking about `git config` or  Visual Studio prompt. We just focus on coding and get clean diff too on every machine/PC.

**Comment by henon** [comment]
I didn't know it worked that well. I always had to turn autocrlf off because it marked all lines in all files changed and that looked very scary. do you know that effect?

**Comment by vunb** [comment]
yep. previously, i often turn autocrlf off manually via git command. it really annoyed. Now this is not big problem because i can use Github to hide whitespace changes to see the Diff, so we can ignore it. :)

**Comment by Oceania2018** [comment]
image

**Pull request merged**
