### PR TITLE
Simple implementation of 2D transpose

### PR DESCRIPTION
**Pull request by JetstreamRoySprowl**

### CODE REVIEW

**Comment by Nucs** [comment]
@Oceania2018 
In short: No and we probably won't.

At the moment we do not support layout at all.
For now, I'll add support for transpose that will perform a swap of the axes (similar to what changing layout does) and that's it.
We already have quite high complexity code related to `GetIndex` (which is now `GetOffset`) because we need to handle slicing and broadcasting, adding layout will multiply it

**Comment by JetstreamRoySprowl** [comment]
@Oceania2018 : there's an [open PR for transpose](https://github.com/SciSharp/NumSharp/pull/332)

**Comment by Nucs** [comment]
If a user is indeed using a layout 'F' then he can simple transpose the data prior to working with it.
Even save it afterwards to avoid that action in the next time.

**Comment by Nucs** [comment]
@Oceania2018 You are good to go

**Comment by Nucs** [comment]
After reviewing how `numpy` performs transpose;
`np.transpose` and many other relies on `np.swapaxes`.
This implementation is a solid `2d-2d` transpose but unless its `nd-nd`, I rather leave `np.transpose` unimplemented.
Thanks a lot though.

**Pull request closed without merging**
